apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-review1
  labels:
    version: v1
    app: mamadou1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mamadou1
      version: v1
  template:
    metadata:
      labels:
        app: mamadou1
        version: v1
    spec:
      containers:
      - name: shopreview1-container
        image: mngouhouo/mngouhouo:espresso-reviews
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_VERSION
          value: "v1"
---
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-reviews-svc
spec:
  selector:
    app: mamadou1
    version: v1
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-review1-service-account
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shop-review1-pdb
spec:
  selector:
    matchLabels:
      app: mamadou1
      version: v1
  minAvailable: 1
